apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: harness-manager
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: "50%"
  selector:
   matchLabels:
    app: harness-manager
